### ISSUE TITLE
Overflow issue persists

### ISSUE THREAD

**Issue by LeoniePhiline** [ronan-hello/matomo-google-theme#3]
Symptom:

![grafik](https://user-images.githubusercontent.com/22329650/204008962-efd114d5-5ba3-4d4b-9b53-8a5ecdd99dfb.png)
![grafik](https://user-images.githubusercontent.com/22329650/204009537-b15d60b4-c8ac-4e79-bc63-edd64cae44b4.png)

Fix:

![grafik](https://user-images.githubusercontent.com/22329650/204009796-9e49009b-4170-406c-89db-609e7b9b5ed4.png)

(Disable `overflow: hidden` on `.widget .widgetContent .dataTable`.)

**Comment by ronan-hello** [comment]
Problem solved with compatibility to dataTable border-radius, an other solution have been applied.
Problem solved, thank you for opening this issue ! :)
