### ISSUE TITLE
Font family slightly too bold in Mac devices

### ISSUE THREAD

**Issue by gorfo66** [ronan-hello/matomo-google-theme#5]
Hello
we like your theme, but on MacOS the fonts look slightly too bold.
This a very common issue on Mac that can be fixed by disabling the font-smoothing

I tried to contribute to your project but got rejected.
Can you please have a look and add the following code into your styles ?

`* {
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-rendering: optimizeLegibility;
}`

**Comment by ronan-hello** [comment]
Hi,

Thank you for opening this issue !
All is fixed right now.
